// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'error-disabled'
  | 'error-missing-api-base'
  | 'error-missing-api-key'
  | 'error-missing-model'
  | 'error-no-selection'
  | 'main-window-title'
  | 'menu-generate-tags'
  | 'pref-api-base-url'
  | 'pref-api-key'
  | 'pref-debug'
  | 'pref-description'
  | 'pref-enable'
  | 'pref-fallback-attachment-text'
  | 'pref-help'
  | 'pref-max-tags'
  | 'pref-model'
  | 'pref-preserve-existing-tags'
  | 'pref-timeout-ms'
  | 'pref-title'
  | 'pref-user-rules'
  | 'pref-user-rules-help'
  | 'prefs-title'
  | 'progress-failure'
  | 'progress-item-running'
  | 'progress-start'
  | 'progress-summary'
  | 'startup-finish';
