// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "apiBaseURL": string;
      "apiKey": string;
      "model": string;
      "apiExtraParams": string;
      "llmConfigs": string;
      "activeLLMConfigId": string;
      "userRules": string;
      "collectionRules": string;
      "maxTags": number;
      "maxConcurrentRequests": number;
      "requestsPerSecond": number;
      "preserveExistingTags": boolean;
      "fallbackToAttachmentText": boolean;
      "enableCollectionRouting": boolean;
      "debug": boolean;
    };
  }
}
